### ISSUE TITLE
0.23.27 Introduces HelloRetryRequest When Connecting to Non-PQ FIPS TLS servers

### ISSUE THREAD

**Issue by RobMor** [rustls/rustls#2495]
**Checklist**
* [X] I've searched the issue tracker for similar bugs.

**Describe the bug**
After updating rustls to 0.23.27 which enables `prefer-post-quantum` by default, connections to FIPS TLS servers that don't support the post-quantum algorithms have to go through a HelloRetryRequest to negotiate down to FIPS non-PQ KeyShare algorithms like `SECP256R1`.

It would be nice if the extra round trip wasn't required in the default configuration.

It might make more sense to use a post-quantum algorithm that has a FIPS compliant "fallback" like `SECP256R1MLKEM768` when rustls is running in FIPS mode. That way in the handshake rustls will send both the PQ and non-PQ KeyShare options, instead of just the PQ option like it does now. That would prevent a round trip even when talking to non-PQ FIPS servers.

In the meantime it's easy enough to mitigate by just disabling `prefer-post-quantum`.

**To Reproduce**
1. Use rustls with `fips` feature enabled to connect to a server that supports only secp256r1.
2. Observe that with rustls 0.23.26 there's no HelloRetryRequest, while in 0.23.27 there is.

`Cargo.toml`:
```toml
[package]
name = "repro"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.4"
axum-server = { version = "0.7.2", features = ["tls-rustls"] }
rcgen = "0.13.2"
reqwest = { version = "0.12.20", features = ["rustls-tls"] }
rustls = { version = "0.23.27", features = ["fips"] }
tokio = { version = "1.45.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
```

`client.rs`:
```rust
#[tokio::main]
async fn main() {
    tracing_subscriber::fmt::init();

    rustls::crypto::aws_lc_rs::default_provider().install_default().unwrap();

    let client = reqwest::ClientBuilder::new()
        .use_rustls_tls()
        .danger_accept_invalid_certs(true)
        .build()
        .unwrap();

    let resp = client.get("https://127.0.0.1:8000")
        .send().await.unwrap()
        .text().await.unwrap();

    println!("{}", resp);
}
```

`server.rs`
```rust
#[tokio::main]
async fn main() {
    tracing_subscriber::fmt::init();

    let rcgen::CertifiedKey { cert, key_pair } = rcgen::generate_simple_self_signed(["localhost".to_string()]).unwrap();

    let mut crypto_provider = rustls::crypto::default_fips_provider();
    crypto_provider.kx_groups = vec![rustls::crypto::aws_lc_rs::kx_group::SECP256R1];
    crypto_provider.install_default().unwrap();

    let config = axum_server::tls_rustls::RustlsConfig::from_der(vec![cert.der().to_vec()], key_pair.serialized_der().to_vec()).await.unwrap();

    let app = axum::Router::new().route("/", axum::routing::get(|| async { "Hello, World!" }));

    axum_server::bind_rustls(std::net::SocketAddr::from(([127, 0, 0, 1], 8000)), config)
        .serve(app.into_make_service())
        .await
        .unwrap()
}
}
```

Running:

```bash
RUST_LOG=trace cargo run --bin client
```

Output:

```
...
2025-06-15T06:20:24.288878Z TRACE rustls::client::hs: Got HRR HelloRetryRequest { legacy_version: TLSv1_2, session_id: XXX, cipher_suite: TLS13_AES_256_GCM_SHA384, extensions: [KeyShare(secp256r1), SupportedVersions(TLSv1_3)] }
...
```

**Applicable Version(s)**
The issue was introduced in 0.23.27 with the enablement of the use of PQ algorithms by default.

**Expected behavior**

This is an expected behavior based on how rustls is configured right now.

Maybe this shouldn't be a bug report, but it seemed like the best template for starting a discussion on this.

**Additional context**

X25519 is not FIPS: https://github.com/rustls/rustls/issues/1992

So when `X25519MLKEM768` is used in a handshake, the bare `X25519` KeyShare cannot be used, like it would be for non-FIPS handshakes: https://github.com/rustls/rustls/blob/main/rustls/src/client/hs.rs#L328-L331
